### User Registration with LocalStrategy
POST {{base_url}}/auth/localStrategy/signup
content-type: application/json

{
  "email": "123456@gmail.com",
  "password": "123456"
}


### User Login with LocalStrategy
POST {{base_url}}/auth/localStrategy/login
content-type: application/json

{
  "email": "123456@gmail.com",
  "password": "123456"
}

### User Login and return Jwt Token
POST {{base_url}}/auth/login
content-type: application/json

{
  "email": "123456@gmail.com",
  "password": "123456"
}

> {%
  client.global.set("jwt_token", response.body.access_token);
%}

### Get User's Profile
GET {{base_url}}/auth/profile
content-type: application/json
Authorization: Bearer {{jwt_token}}
